import type { Ad } from "kijiji-scraper";

export const mockListings: Ad[] = [
	{
		title: "307-55 Mercer Street, Toronto, Ontario M5V 3W2 - 307-55 Mercer S",
		description: `** OPEN 24/7 - CALL: 905-385-8150 **2 Bedrooms + Den, 2 Bathrooms, Near Parks, Public Transportation, Bus Stops, Schools, Shopping Malls, Grocery Stores, Restaurants, Bars and Sports Clubs. The unit also has an Upgraded Kitchen, Formica Countertops, Laminate Floors, Upgraded Bathrooms, and Tons of Natural Light.SCHEDULE SHOWING - CLICK BELOW:https://zfrmz.com/rOT7uZLfArzfblVRr0wf?unit_id=3494024000651504619&unit_name=307-55-Mercer-Street,-Toronto,-Ontario-M5V-3W2&bedroom=2-+-Den&bathroom=2&parking=0&occupants=4ADDRESS AND INTERSECTION:307-55 Mercer Street, Toronto, Ontario M5V 3W2Wellington Street West and Blue Jays WayPRICE AND SPECIAL OFFERS:$3,800.00Enjoy Special Offers From Our Partners: Rogers, Telus, Bell, Apollo Insurance, The BrickUNIT FEATURES: 2 Bedrooms + Den | 2 Bathrooms - Brand New - Never Lived in Condominium- Upgraded Kitchen- Formica Countertops - Paneled Appliances - Dishwasher - Ensuite laundry - Laminate Floors - 9 Foot Ceiling - Upgraded Bathrooms - Regular Closets- Upgraded Back Splash - Ensuite Bathroom - Lawn and Snow Removal: Included - Personal Thermostat - Tons of Natural Light BUILDING AMENITIES: - Bicycle Storage - 24/7 Security and Concierge- Enter Phone System- Lobby/Lounge- Fitness Center/Gym- Yoga / Pilates Room (YPR)- Party Room- Meeting Room- Rec Room- Library- Movie Room- Guest Suites- Sauna- Basketball Court- Laundry Facilities- Elevators- Wheelchair AccessAvailable Immediately!!** OPEN 24/7 - CALL: 905-385-8150 ** SCHEDULE SHOWING - CLICK BELOW: https://zfrmz.com/rOT7uZLfArzfblVRr0wf?unit_id=3494024000651504619&unit_name=307-55-Mercer-Street,-Toronto,-Ontario-M5V-3W2&bedroom=2-+-Den&bathroom=2&parking=0&occupants=4READY FOR YOU:Your new home will be spotlessly clean before move-in!Building Overivew** OPEN 24/7 - CALL: 905-385-8150 **2 Bedrooms + Den, 2 Bathrooms, Near Parks, Public Transportation, Bus Stops, Schools, Shopping Malls, Grocery Stores, Restaurants, Bars and Sports Clubs. The unit also has an Upgraded Kitchen, Formica Countertops, Laminate Floors, Upgraded Bathrooms, and Tons of Natural Light.SCHEDULE SHOWING - CLICK BELOW:https://zfrmz.com/rOT7uZLfArzfblVRr0wf?unit_id=3494024000651504619&unit_name=307-55-Mercer-Street,-Toronto,-Ontario-M5V-3W2&bedroom=2-+-Den&bathroom=2&parking=0&occupants=4ADDRESS AND INTERSECTION:307-55 Mercer Street, Toronto, Ontario M5V 3W2Wellington Street West and Blue Jays WayPRICE AND SPECIAL OFFERS:$3,800.00Enjoy Special Offers From Our Partners: Rogers, Telus, Bell, Apollo Insurance, The BrickUNIT FEATURES: 2 Bedrooms + Den | 2 Bathrooms - Brand New - Never Lived in Condominium- Upgraded Kitchen- Formica Countertops - Paneled Appliances - Dishwasher - Ensuite laundry - Laminate Floors - 9 Foot Ceiling - Upgraded Bathrooms - Regular Closets- Upgraded Back Splash - Ensuite Bathroom - Lawn and Snow Removal: Included - Personal Thermostat - Tons of Natural Light BUILDING AMENITIES: - Bicycle Storage - 24/7 Security and Concierge- Enter Phone System- Lobby/Lounge- Fitness Center/Gym- Yoga / Pilates Room (YPR)- Party Room- Meeting Room- Rec Room- Library- Movie Room- Guest Suites- Sauna- Basketball Court- Laundry Facilities- Elevators- Wheelchair AccessAvailable Immediately!!** OPEN 24/7 - CALL: 905-385-8150 ** SCHEDULE SHOWING - CLICK BELOW: https://zfrmz.com/rOT7uZLfArzfblVRr0wf?unit_id=3494024000651504619&unit_name=307-55-Mercer-Street,-Toronto,-Ontario-M5V-3W2&bedroom=2-+-Den&bathroom=2&parking=0&occupants=4READY FOR YOU:Your new home will be spotlessly clean before move-in!Building Features2 Bedrooms + Den, 2 Bathrooms, Near Parks, Public Transportation, Bus Stops, Schools, Shopping Malls, Grocery Stores, Restaurants, Bars and Sport Clubs. The unit also has an Upgraded Kitchen, Formica Countertops, Laminate Floors, Upgraded Bathrooms, and Tons of Natural Light.Location DetailsNear Parks, Public Transportation, Bus Stops, Schools, Shopping Malls, Grocery Stores, Restaurants, Bars and Sports Clubs.Suite Details"Welcome to your urban oasis at 307-55 Mercer Street, Toronto! This modern and spacious condominium boasts 2 bedrooms plus a den and 2 bathrooms spread across approximately 750 square feet, offering the perfect blend of comfort and style in the heart of Toronto's vibrant Entertainment District. Featuring sleek finishes, an open-concept layout, and ample natural light, this unit is ideal for professionals, couples, or small families seeking a chic downtown living experience. Enjoy the convenience of a designated locker for extra storage. With its prime location near top restaurants, shops, and entertainment venues, as well as easy access to public transit and major highways, this condo offers unparalleled convenience and lifestyle. Don't miss out on the opportunity to call this place home. Schedule your viewing today!"Utilities Included:WaterSewageGarbage CollectionInternet`,
		date: new Date(Date.parse("2024-04-26T12:30:00.000Z")),
		image:
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/f5/f53ff6b5-f9a0-46f5-ae5d-6e4cc5a960db?rule=kijijica-1600-jpg",
		images: [
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/f5/f53ff6b5-f9a0-46f5-ae5d-6e4cc5a960db?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/78/784d1f8b-e497-442c-b6ea-d728109dddfb?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/ac/ac098cb3-ebaf-450c-8441-0d575a09adbf?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/94/94cf71c0-663a-4838-ab08-021ef6e56509?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/38/38e4164d-fa73-4fba-a511-31451b635948?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/6b/6b561a2c-788b-48fb-9c60-bb5fc0b53c18?rule=kijijica-1600-jpg",
		],
		attributes: {
			forrentbyhousing: "reprofessional",
			unittype: "apartment",
			numberbedrooms: 2.5,
			numberbathrooms: 2,
			agreementtype: "one-year",
			petsallowed: "limited",
			areainfeet: 750,
			furnished: false,
			laundryinunit: true,
			laundryinbuilding: true,
			dishwasher: true,
			fridgefreezer: true,
			airconditioning: false,
			yard: false,
			balcony: false,
			smokingpermitted: false,
			gym: false,
			pool: false,
			concierge: false,
			twentyfourhoursecurity: false,
			bicycleparking: false,
			storagelocker: false,
			elevator: true,
			wheelchairaccessible: false,
			braillelabels: false,
			audioprompts: false,
			barrierfreeentrancesandramps: false,
			visualaids: false,
			accessiblewashroomsinsuite: false,
			hydro: false,
			heat: false,
			water: true,
			cabletv: false,
			internet: true,
			numberparkingspots: 0,
			rentalsvirtualoptions: "[virtualtour]",
			price: 3800,
			location: {
				latitude: 43.6453,
				longitude: -79.39172,
				mapAddress: "55 Mercer Street, Toronto, ON, M5V 3W2",
				province: "ontario",
				mapRadius: 0,
			},
			type: "OFFER",
		},
		url: "https://www.kijiji.ca/v-apartments-condos/city-of-toronto/307-55-mercer-street-toronto-ontario-m5v-3w2-307-55-mercer-s/1691853055",
		id: "1691853055",
		scrape: [],
		isScraped: [],
	},
	{
		title: "Furnished 1 Bedroom Basement For Rent!",
		description:
			"Furnished 1 Bedroom Basement For Rent! Walking Distance to the Bus Stop! Close to TTC Bus Routes 116, 86, 12, & 905, and GO Train, Subway, & RT Stations. Schools, Shopping Centres, and all other Amenities. Sharing Kitchen & Washroom with one other person. Located in Scarborough, Toronto, Just South of Markham Road & Kingston Road. $1,250/month. New Immigrants and Refugees Are Welcome! Available Now! If you are interested, please call (416)459-6155.",
		date: new Date(Date.parse("2024-04-26T12:23:43.000Z")),
		image:
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/aa/aa536b9b-b458-40d9-8818-ebea8bc16689?rule=kijijica-1600-jpg",
		images: [
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/aa/aa536b9b-b458-40d9-8818-ebea8bc16689?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/78/78a934d6-2c57-48c2-b906-854cfac0a73d?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/1b/1bf91ba8-429a-4690-8448-bcb4aa0a328d?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/62/62273cd7-21b1-4fed-baae-eecfee84ce97?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/01/01fee738-bb74-40c0-9aee-87355a84598e?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/7d/7d145287-7c32-4560-8da7-02bca60beb55?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/01/01129331-ca79-4910-a637-32f6d69097e2?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/ee/ee740b07-16e2-445f-960b-b2ec4ede48eb?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/31/3174f505-6e98-4919-a8b1-bcc7f253bf3f?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-dealer-ads/images/41/413eeae3-7503-4d0b-aa34-dba6bcb20b87?rule=kijijica-1600-jpg",
		],
		attributes: {
			forrentbyhousing: "ownr",
			unittype: "basement-apartment",
			numberbedrooms: 1,
			numberbathrooms: 1,
			agreementtype: "month-to-month",
			dateavailable: "2024-04-26T00:00:00.000Z",
			petsallowed: "limited",
			areainfeet: 1,
			furnished: true,
			laundryinunit: false,
			laundryinbuilding: false,
			dishwasher: false,
			fridgefreezer: true,
			airconditioning: false,
			yard: false,
			balcony: false,
			smokingpermitted: 2,
			gym: false,
			pool: false,
			concierge: false,
			twentyfourhoursecurity: false,
			bicycleparking: false,
			storagelocker: false,
			elevator: false,
			wheelchairaccessible: false,
			braillelabels: false,
			audioprompts: false,
			barrierfreeentrancesandramps: false,
			visualaids: false,
			accessiblewashroomsinsuite: false,
			hydro: true,
			heat: true,
			water: true,
			cabletv: false,
			internet: false,
			numberparkingspots: 0,
			price: 1250,
			location: {
				latitude: 43.76357,
				longitude: -79.18871,
				mapAddress: "Scarborough, ON M1E",
				province: "ontario",
				mapRadius: 0,
			},
			type: "OFFER",
			visits: 2,
		},
		url: "https://www.kijiji.ca/v-apartments-condos/city-of-toronto/furnished-1-bedroom-basement-for-rent/1691858461",
		id: "1691858461",
		scrape: [],
		isScraped: [],
	},
	{
		title: "One bedroom, Utilities included, Steps to Finch subway",
		description:
			'Beautiful Location. Steps To Yonge & Finch Subway Station -- Welcome To "Monet" Stylish, Beautiful, Well Maintained Condo In The Heart Of North York. 1 Bedroom With 1 Wr. Very Bright Unit, With Open Balcony, Open Concept Style, Modern Kitchen, Hardwood Floors, Granite Counter Top, Extra Large Parking, 24 Hr Concierge, Rec, Media, Billiard, Business Centre, Steam Rooms, Guest Suites, Indoor Pool.',
		date: new Date(Date.parse("2024-04-26T12:23:14.000Z")),
		image:
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/71/71fb3ec1-41b2-467c-85ad-c6a072029957?rule=kijijica-1600-jpg",
		images: [
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/71/71fb3ec1-41b2-467c-85ad-c6a072029957?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/e0/e0ceceb5-8207-496a-952a-c4582dfca6e3?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/36/367e4f35-39ef-494e-b0f9-670885fd020e?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/55/55db16a7-e3f9-44b6-b9f4-18b3e7348cc1?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/8b/8b13561f-3cd6-4067-ab5a-284b69483259?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/56/56d5c5a6-fecf-44f0-9676-7a99e2d3630c?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/28/284bec84-16be-4367-b1dc-08c734b78b0b?rule=kijijica-1600-jpg",
		],
		attributes: {
			forrentbyhousing: "ownr",
			unittype: "condo",
			numberbedrooms: 1,
			numberbathrooms: 1,
			agreementtype: "one-year",
			dateavailable: "2024-04-25T00:00:00.000Z",
			petsallowed: "limited",
			areainfeet: 600,
			furnished: false,
			laundryinunit: true,
			laundryinbuilding: false,
			dishwasher: true,
			fridgefreezer: true,
			airconditioning: true,
			yard: false,
			balcony: true,
			smokingpermitted: 2,
			gym: true,
			pool: true,
			concierge: true,
			twentyfourhoursecurity: true,
			bicycleparking: true,
			storagelocker: false,
			elevator: true,
			wheelchairaccessible: true,
			braillelabels: false,
			audioprompts: false,
			barrierfreeentrancesandramps: true,
			visualaids: false,
			accessiblewashroomsinsuite: false,
			hydro: true,
			heat: true,
			water: true,
			cabletv: false,
			internet: false,
			numberparkingspots: 1,
			price: 2450,
			location: {
				latitude: 43.77734,
				longitude: -79.41275,
				mapAddress: "Byng Avenue, North York, ON",
				province: "ontario",
				mapRadius: 0,
			},
			type: "OFFER",
			visits: 1,
		},
		url: "https://www.kijiji.ca/v-apartments-condos/city-of-toronto/one-bedroom-utilities-included-steps-to-finch-subway/1691858433",
		id: "1691858433",
		scrape: [],
		isScraped: [],
	},
	{
		title: "2 Bedroom, 1 Bath Basement Apt. for Rent in North York",
		description: "2 Bedroom, 1 Bath Basement Apt. for Rent in North York",
		date: new Date(Date.parse("2024-04-26T12:15:31.000Z")),
		image:
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/86/862774f1-9f43-42f1-8665-0ed93ad8f980?rule=kijijica-1600-jpg",
		images: [
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/86/862774f1-9f43-42f1-8665-0ed93ad8f980?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/ba/ba398427-f233-4015-b566-6d617eb2e484?rule=kijijica-1600-jpg",
		],
		attributes: {
			forrentbyhousing: "ownr",
			unittype: "basement-apartment",
			numberbedrooms: 2,
			numberbathrooms: 1,
			agreementtype: "one-year",
			dateavailable: "2024-05-01T00:00:00.000Z",
			petsallowed: false,
			areainfeet: 500,
			furnished: false,
			laundryinunit: false,
			laundryinbuilding: true,
			dishwasher: false,
			fridgefreezer: false,
			airconditioning: true,
			yard: true,
			balcony: false,
			smokingpermitted: 2,
			gym: false,
			pool: false,
			concierge: false,
			twentyfourhoursecurity: false,
			bicycleparking: false,
			storagelocker: false,
			elevator: false,
			wheelchairaccessible: false,
			braillelabels: false,
			audioprompts: false,
			barrierfreeentrancesandramps: false,
			visualaids: false,
			accessiblewashroomsinsuite: false,
			hydro: false,
			heat: true,
			water: true,
			cabletv: false,
			internet: false,
			numberparkingspots: 0,
			price: 1950,
			location: {
				latitude: 43.78502,
				longitude: -79.33547,
				mapAddress: "North York, ON M2J 3R6",
				province: "ontario",
				mapRadius: 152.7176019428396,
			},
			type: "OFFER",
			visits: 56,
		},
		url: "https://www.kijiji.ca/v-apartments-condos/city-of-toronto/2-bedroom-1-bath-basement-apt-for-rent-in-north-york/1691732343",
		id: "1691732343",
		scrape: [],
		isScraped: [],
	},
	{
		title: "One bedroom, Steps to Bayview subway,Utilities included",
		description:
			"Welcome To Chrysler By Daniels, Located In Serene Bayview Village, This Well Laid Out, Open Concept 1 Bed, 1 Bath Unit Boasts Floor toCeiling Windows, And A Spacious Open Concept Living. World Class Amenities Include Virtual Golf, Billiards, Swimming Pool, Sauna, Gym,Party Room, Multipurpose Room, Ping Pong, and Much More. Minutes Away From TTC, Groceries, Trendy Restaurants, Shops (Bayview VillageShopping Centre), And Much More! It's The Perfect Place To Call Home.\n" +
			"\n" +
			"Extras:1 Parking and 1 Locker Included. Appliances Include Washer, Dryer, Stove, Fridge, Dishwasher, And Range Hood For The Tenants Use.\n" +
			"\n" +
			"Inclusions:All Utilties Are Included (Water, Hydro, Gas)",
		date: new Date(Date.parse("2024-04-26T12:12:46.000Z")),
		image:
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/11/1132fe6e-ea03-4970-b487-56da645c89ae?rule=kijijica-1600-jpg",
		images: [
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/11/1132fe6e-ea03-4970-b487-56da645c89ae?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/e4/e492a541-1496-4002-a84c-1254f1a1ea65?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/35/3563908c-bf44-4103-b828-c4dae605b551?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/0c/0c6222b6-b3ae-4012-a7a2-28784ca3ed6f?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/a4/a4c58db8-e500-4a37-bc44-a392d311cce7?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/9f/9ff42386-0994-4e7a-a6f9-b79b236022e7?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/d4/d4553213-a703-4b5b-9f2e-7cc23c190767?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/6b/6bbe29dd-5e67-408f-a2f1-192e0580c681?rule=kijijica-1600-jpg",
			"https://media.kijiji.ca/api/v1/ca-prod-fsbo-ads/images/82/82bc1b64-bc1a-4596-962a-2b0b3c19152f?rule=kijijica-1600-jpg",
		],
		attributes: {
			forrentbyhousing: "ownr",
			unittype: "condo",
			numberbedrooms: 1,
			numberbathrooms: 1,
			agreementtype: "one-year",
			dateavailable: "2024-04-25T00:00:00.000Z",
			petsallowed: "limited",
			areainfeet: 600,
			furnished: false,
			laundryinunit: true,
			laundryinbuilding: false,
			dishwasher: true,
			fridgefreezer: true,
			airconditioning: true,
			yard: false,
			balcony: true,
			smokingpermitted: 2,
			gym: true,
			pool: true,
			concierge: true,
			twentyfourhoursecurity: true,
			bicycleparking: true,
			storagelocker: true,
			elevator: true,
			wheelchairaccessible: true,
			braillelabels: false,
			audioprompts: false,
			barrierfreeentrancesandramps: true,
			visualaids: false,
			accessiblewashroomsinsuite: false,
			hydro: true,
			heat: true,
			water: true,
			cabletv: false,
			internet: false,
			numberparkingspots: 1,
			price: 2400,
			location: {
				latitude: 43.76542,
				longitude: -79.38294,
				mapAddress: "Rean Drive, North York, ON",
				province: "ontario",
				mapRadius: 0,
			},
			type: "OFFER",
			visits: 1,
		},
		url: "https://www.kijiji.ca/v-apartments-condos/city-of-toronto/one-bedroom-steps-to-bayview-subway-utilities-included/1691857748",
		id: "1691857748",
		scrape: [],
		isScraped: [],
	},
];
